name: BetterCoins
main: com.bettercoins.BetterCoins
version: 5.01
authors: [Nijikokun]
commands:
    money:
        description: Controls account balances and more
        usage:
    bank:
        description: Control, list, create, and do various bank features
        usage: